env:
  browser: true
  commonjs: true
  es2021: true
extends: airbnb-base
parserOptions:
  ecmaVersion: latest
rules:
  {
    'no-console': 'off',
    'no-param-reassign': 'off',
    'no-underscore-dangle': 'off',
    'consistent-return': 'off',
    'operator-linebreak': 'off',
    'comma-dangle': 'off',
    'implicit-arrow-linebreak': 'off',
  }
