version: '3'
services:
  foodtime-api:
    image: adam-kostuch/foodtime-api
    build: .
    networks:
      - backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui_container
    ports:
      - "8090:8080"
    volumes:
      - ./swagger:/usr/share/nginx/html/swagger
    environment:
      API_URL: 'swagger/openapi.yaml'

  web-cli:
    image: adam-kostuch/foodtime-api
    links:
      - mongo
    networks:
      - backend
    command: sh


networks:
  backend:
    driver: bridge
